/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.ConfigureBusiness;
import Business.Customer;
import Business.Flight;
import Business.Gender;
import Business.Seat;
import Business.Ticket;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bobba
 */
public class CustomerDetailsEntryJPanel extends javax.swing.JPanel {

    static String numbersRegex = "[0-9]+";
    static String lettersRegex = "^[\\p{L} .'-]+$";
    /**
     * Creates new form CustomerDetailsEntryJPanel
     */
    private JPanel rightPanel;
    private Flight flight;
    private TravelAgency travelAgency;

    CustomerDetailsEntryJPanel(JPanel rightPanel, TravelAgency travelAgency, Flight flight) {

        initComponents();
        this.rightPanel = rightPanel;
        this.flight = flight;
        this.travelAgency = travelAgency;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        mobileTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        mailIdTxt = new javax.swing.JTextField();
        proccedBookBtn = new javax.swing.JButton();
        genderBox = new javax.swing.JComboBox<>();

        jLabel1.setText("Enter Your Details");

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Mobile Number");

        jLabel4.setText("Age");

        jLabel5.setText("Gender");

        jLabel6.setText("Email Id");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        mobileTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileTxtActionPerformed(evt);
            }
        });

        ageTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtActionPerformed(evt);
            }
        });

        mailIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailIdTxtActionPerformed(evt);
            }
        });

        proccedBookBtn.setText("Proceed With Booking");
        proccedBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proccedBookBtnActionPerformed(evt);
            }
        });

        genderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn)
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(210, 210, 210))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(154, 154, 154)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mailIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mobileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proccedBookBtn))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mobileTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(proccedBookBtn)
                .addContainerGap(91, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void mobileTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileTxtActionPerformed

    private void ageTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtActionPerformed

    private void mailIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailIdTxtActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void proccedBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proccedBookBtnActionPerformed
        // Take customer details and add customer to customer directry
        //Add ticket to list in customer 
        // change the seat of avaliablity
        if (nameTxt.getText().equals("") || mobileTxt.getText().equals("") || mailIdTxt.getText().equals("") || ageTxt.getText().equals("")) //Search fir cusrtomer and we can do even login in this 
        {
            JOptionPane.showMessageDialog(null, "one or more fields are required");
            return;
        }

        try {
            int age = Integer.parseInt(ageTxt.getText());
        } catch (NumberFormatException ex) { // handle your exception
            JOptionPane.showMessageDialog(null, "Age should only be numbers.");
            return;
        }

        if (!mobileTxt.getText().matches(numbersRegex)) {
            JOptionPane.showMessageDialog(null, "Mobile number should only be numbers.");
            return;
        }

        if (!nameTxt.getText().matches(lettersRegex)) {
            JOptionPane.showMessageDialog(null, "Name should only be letters.");
            return;
        }

        Customer c = travelAgency.searchCustomerByMail(mailIdTxt.getText());
        if (c == null) {
            c = travelAgency.createNewCustomer();
        }

        c.setAge(Integer.parseInt(ageTxt.getText()));
        c.setEmailId(mailIdTxt.getText());
        c.setGender(Gender.valueOf(String.valueOf(genderBox.getSelectedItem())));
        c.setMobileNumber(mobileTxt.getText());
        c.setName(nameTxt.getText());

        Ticket t = new Ticket();
        t.setArrivalTime(flight.getArrivalTime());
        t.setBookingDate(LocalDate.now() + " " + LocalTime.now().getHour() + ":" + LocalTime.now().getMinute());
        t.setDeparture(flight.getDeparture());
        t.setDepartureTime(flight.getDepartureTime());
        t.setDestination(flight.getDestination());
        t.setNumber(flight.getNumber()); //flight number
        t.setPnr(ConfigureBusiness.getSaltString().toUpperCase());

        t.setSeatNumber(getFirstAvalSeat(flight.getSeats()));//Need to get teh seat number on the combination selected by ccustomer
        if (c.getTickets() == null) {
            List<Ticket> tks = new ArrayList<>();
            tks.add(t);
            c.setTickets(tks);
        } else {
            c.getTickets().add(t);
        }

        SuccessfulBookingJPanel successfulBookingJPanel = new SuccessfulBookingJPanel(c, travelAgency, rightPanel, flight);

        rightPanel.add("SuccessfulBookingJPanel", successfulBookingJPanel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);

    }//GEN-LAST:event_proccedBookBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> genderBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mailIdTxt;
    private javax.swing.JTextField mobileTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JButton proccedBookBtn;
    // End of variables declaration//GEN-END:variables

    private String getFirstAvalSeat(List<Seat> seats) {

        String seatNumer = null;
        for (Seat s : seats) {
            if (s.isIsAvailable()) {
                seatNumer = s.getSeatNumber();
                s.setIsAvailable(false);
                break;
            }
        }

        return seatNumer;

    }
}
