/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Customer;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bobba
 */
public class SuccessfulBookingJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SuccessfulBookingJPanel
     */
    private JPanel cardSequenceJPanel;
    private Flight flight;
    private TravelAgency travelAgency;
    private Customer customer;

    SuccessfulBookingJPanel(Customer customer, TravelAgency travelAgency, JPanel cardSequenceJPanel, Flight flight) {
        initComponents();
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.customer = customer;
        this.travelAgency = travelAgency;
        this.flight = flight;
        String s = LabelTxt.getText().replaceFirst("FROM_", flight.getDeparture());
        String str = s.replaceFirst("TO_", flight.getDestination());
        LabelTxt.setText(str);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewCustomerBookingTxt = new javax.swing.JButton();
        LabelTxt = new javax.swing.JLabel();
        hmBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Congratulations!!!!");

        viewCustomerBookingTxt.setText("View Customer Bookings");
        viewCustomerBookingTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomerBookingTxtActionPerformed(evt);
            }
        });

        LabelTxt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LabelTxt.setText("Your ticket has been successfully booked from FROM_ to TO_");

        hmBtn.setText("Back To Home");
        hmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hmBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(LabelTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(hmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(viewCustomerBookingTxt)))
                .addGap(165, 165, 165))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(hmBtn)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(LabelTxt)
                .addGap(37, 37, 37)
                .addComponent(viewCustomerBookingTxt)
                .addGap(292, 292, 292))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void hmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hmBtnActionPerformed
        cardSequenceJPanel.removeAll();

    }//GEN-LAST:event_hmBtnActionPerformed

    private void viewCustomerBookingTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomerBookingTxtActionPerformed
        ViewCustomerBookingsJPanel viewCustomerBookingsJPanel = new ViewCustomerBookingsJPanel(travelAgency, customer, cardSequenceJPanel);
        cardSequenceJPanel.add("ViewCustomerBookingsJPanel", viewCustomerBookingsJPanel);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_viewCustomerBookingTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTxt;
    private javax.swing.JButton hmBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewCustomerBookingTxt;
    // End of variables declaration//GEN-END:variables
}
